update crossvalidate caveat and update adapted spark version
NVIDIA/spark-rapids-examples pull request #137
Opened 2022-03-24 10:39 UTC by nvliyuan

Signed-off-by: liyuan <yuali@nvidia.com>
update cross-validate caveat and update adapted spark version

2022-03-24 10:44 UTC, nvliyuan commented
target to #133 and #134

2022-03-24 10:59 UTC, nvliyuan commented
verified build step and some databricks 10.4 works, but not all
![image](https://user-images.githubusercontent.com/84758614/159902144-4acaa99f-bbd3-4c6c-aaa5-445ba407b809.png)

2022-03-24 15:57 UTC, viadea requested changes

2022-03-24 15:57 UTC, viadea commented on examples/Spark-ETL+XGBoost/README.md
> +because if not the customized cross-validator will submit multi xgboost training jobs and spark may schedule the different
```suggestion
otherwise the customized cross-validator will submit multiple xgboost training jobs and spark may schedule the different 
```

2022-03-24 15:57 UTC, viadea commented on examples/Spark-ETL+XGBoost/README.md
> +xgboost training tasks into one executor simultaneously which will cause issues.
```suggestion
xgboost training tasks into one executor simultaneously and trigger 
[issue-131](https://github.com/NVIDIA/spark-rapids-examples/issues/131).
```

2022-03-25 01:51 UTC, nvliyuan commented on examples/Spark-ETL+XGBoost/README.md
> +xgboost training tasks into one executor simultaneously which will cause issues.
updated, thanks

2022-03-25 01:51 UTC, nvliyuan commented on examples/Spark-ETL+XGBoost/README.md
> +because if not the customized cross-validator will submit multi xgboost training jobs and spark may schedule the different
updated, thanks

2022-03-25 22:51 UTC, viadea commented on examples/Spark-ETL+XGBoost/README.md
> +For the CrossValidator job, we need to set `spark.task.resource.gpu.amount=1` to submit xgboost training jobs sequentially,
```suggestion
For the CrossValidator job, we need to set `spark.task.resource.gpu.amount=1` to allow only 1 training task running on 1 GPU(executor),
```

2022-03-25 22:52 UTC, viadea commented on examples/Spark-ETL+XGBoost/README.md
> +otherwise the customized cross-validator will submit multiple xgboost training jobs and spark may schedule the different
```suggestion
otherwise the customized CrossValidator may schedule more than 1 
```

2022-03-25 22:53 UTC, viadea commented on examples/Spark-ETL+XGBoost/README.md
> +For the CrossValidator job, we need to set `spark.task.resource.gpu.amount=1` to submit xgboost training jobs sequentially,
I may need to change the statement a little bit after talking with @GaryShen2008  and @wbo4958 for this issue. 
So I changed the wording.

2022-03-29 17:00 UTC, viadea submitted a review, later dismissed

2022-03-30 02:24 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/aws/ec2.md
> +## Launch EC2 and Configure Spark 3.2
thanks, updated

2022-03-30 16:58 UTC, gerashegalov approved these changes

2022-04-02 02:58 UTC, merged