update versions for v2204 release
NVIDIA/spark-rapids-examples pull request #149
Opened 2022-04-14 01:59 UTC by nvliyuan

Signed-off-by: liyuan <yuali@nvidia.com>
update versions for v2204 release

2022-04-14 02:32 UTC, viadea requested changes

2022-04-14 02:32 UTC, viadea commented on examples/Spark-cuSpatial/gpu-run.sh
> +PLUGIN_VERSION=22.04.0
Here we can not assume cudf jar and rapids jar are always the same. In the past it happened that cudf jar or rapids jar may have a hotfix by itself.

2022-04-14 02:36 UTC, nvliyuan commented on examples/Spark-cuSpatial/gpu-run.sh
> +PLUGIN_VERSION=22.04.0
updated

2022-04-18 02:31 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/csp/databricks/databricks.md
> +    installed.  Users will need to use 21.12.0 or later on Databricks 9.1 LTS ML. In this case use
Why do this change to be 21.12.0?

2022-04-18 02:37 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/databricks/databricks.md
> +    installed.  Users will need to use 21.12.0 or later on Databricks 9.1 LTS ML. In this case use
because we support Databricks 9.1 LTS ML since v21.12, not v22.02

2022-04-18 02:50 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
>      "sudo cp /dbfs/FileStore/jars/xgboost4j_3.0-1.4.2-0.2.0.jar /databricks/jars/spark--maven-trees--ml--9.x--xgboost-gpu--ml.dmlc--xgboost4j-gpu_2.12--ml.dmlc__xgboost4j-gpu_2.12__1.4.1.jar\n",
nit: we also need to update xgboost version to use DMLC release after it's released.

2022-04-18 04:06 UTC, GaryShen2008 commented on examples/Spark-cuML/pca/README.md
> +[rapids-4-spark-ml_2.12-22.04.0-cuda11.jar](https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark-ml_2.12/22.04.0/rapids-4-spark-ml_2.12-22.04.0-cuda11.jar)
nit: Let me confirm if we should release rapids-4-spark-ml 22.04.

2022-04-18 04:07 UTC, GaryShen2008 commented on examples/Spark-cuML/pca/README.md
> +conda install -c rapidsai-nightly -c nvidia -c conda-forge cudf=22.04 python=3.8 -y
@wjxiz1992 Can you confirm if this can use cudf 22.04?

2022-04-19 15:07 UTC, viadea submitted a review, later dismissed

2022-04-20 00:02 UTC, nvliyuan commented
> @nvliyuan @GaryShen2008 should we have another PR to update everything to 1.6.0 xgboost jars and remove pyspark related notebooks?

sure, will not merge this pr before #148 merged.

2022-04-26 02:28 UTC, wjxiz1992 commented on examples/Spark-cuML/pca/README.md
> +conda install -c rapidsai-nightly -c nvidia -c conda-forge cudf=22.04 python=3.8 -y
Let's remove this note, it's been useless since https://github.com/NVIDIA/spark-rapids-ml/pull/39.

2022-04-26 02:28 UTC, wjxiz1992 commented on examples/Spark-cuML/pca/README.md
>  ```
```suggestion

```

2022-04-26 02:28 UTC, wjxiz1992 commented on examples/Spark-cuML/pca/README.md
> +conda install -c rapidsai-nightly -c nvidia -c conda-forge cudf=22.04 python=3.8 -y
```suggestion

```

2022-04-26 02:28 UTC, wjxiz1992 commented on examples/Spark-cuML/pca/README.md
>  ```
```suggestion

```

2022-04-26 02:39 UTC, GaryShen2008 commented on examples/Spark-cuML/pca/README.md
> +[rapids-4-spark-ml_2.12-22.04.0-cuda11.jar](https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark-ml_2.12/22.04.0/rapids-4-spark-ml_2.12-22.04.0-cuda11.jar)
We won't release spark-rapids-ml 22.04, so let's keep using 22.02.

2022-04-26 02:41 UTC, GaryShen2008 approved these changes

2022-04-26 02:42 UTC, merged