PCBS micro-benchmark
NVIDIA/spark-rapids-examples pull request #159
Opened 2022-05-12 19:40 UTC by razajafri

This is micro-benchmark used to compare performance of writing/reading cached batches using PCBS and DefaultCachedBatchSerializer

2022-05-12 19:41 UTC, razajafri commented
@viadea

2022-05-13 08:05 UTC, nvliyuan commented on examples/pcbs-benchmark/src/main/scala/org/apache/spark/sql/execution/columnar/Util.scala
> +        .master("spark://raza-linux-2:7077")
can we make the configs variables? It is better if we can update the params in pcbs-benchmark.sh script

2022-05-13 08:05 UTC, nvliyuan commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +--conf spark.executor.resource.gpu.discoveryScript=./getGpusResources.sh \
I don't find getGpusResources.sh in the repo, should this be updated to ${SPARK_HOME}/examples/src/main/scripts/getGpusResources.sh ?

2022-05-13 09:00 UTC, nvliyuan commented
I spend some time building the jar, due to the terrible urm or maven repository network. Shall we add more comments to guide customers to download and install mvn package manually to save times? Such as
```
wget https://XXX/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar

mvn install:install-file -DcreateChecksum=true -Dpackaging=jar -DgroupId=com.nvidia -DartifactId=rapids-4-spark_2.12 -Dversion=22.06.0-SNAPSHOT -Dclassifier=cuda11 -Dfile=/your-path/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar
```

2022-05-13 09:14 UTC, nvliyuan commented
Do we need to add some sample datasets under ```datasets``` folder?  What are the considerations about parquet file when we test? For example， how does the parquet file size influence the performance.

2022-05-13 09:25 UTC, nvliyuan commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +BENCH_JAR="/home/rjafri/spark-rapids-examples/examples/pcbs-benchmark/target/pcbs-benchmark-1.0-SNAPSHOT.jar"
maybe we should hide personal information from path

2022-05-14 00:18 UTC, razajafri commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +--conf spark.executor.resource.gpu.discoveryScript=./getGpusResources.sh \
The file will be shipped from SPARK_HOME to each executor AFAIK

2022-05-14 00:20 UTC, razajafri commented on examples/pcbs-benchmark/src/main/scala/org/apache/spark/sql/execution/columnar/Util.scala
> +        .master("spark://raza-linux-2:7077")
I have removed the settings from here. 

> I spend some time building the jar, due to the terrible urm or maven repository network. Shall we add more comments to guide customers to download and install mvn package manually to save time? Such as
> 
> ```
> wget https://XXX/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar
> 
> mvn install:install-file -DcreateChecksum=true -Dpackaging=jar -DgroupId=com.nvidia -DartifactId=rapids-4-spark_2.12 -Dversion=22.06.0-SNAPSHOT -Dclassifier=cuda11 -Dfile=/your-path/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar
> ```

This is not necessary I think because the file can be built locally or downloaded however the user wants and put in the `lib` folder

2022-05-14 00:20 UTC, razajafri commented
> I spend some time building the jar, due to the terrible urm or maven repository network. Shall we add more comments to guide customers to download and install mvn package manually to save time? Such as
> 
> ```
> wget https://XXX/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar
> 
> mvn install:install-file -DcreateChecksum=true -Dpackaging=jar -DgroupId=com.nvidia -DartifactId=rapids-4-spark_2.12 -Dversion=22.06.0-SNAPSHOT -Dclassifier=cuda11 -Dfile=/your-path/rapids-4-spark_2.12-22.06.0-20220512.134355-33-cuda11.jar
> ```

This is not necessary I think because the file can be built locally or downloaded however the user wants and put in the `lib` folder

2022-05-14 00:21 UTC, razajafri commented
> Do we need to add some sample datasets under `datasets` folder? What are the considerations about parquet file when we test? For example， how does the parquet file size influence the performance.

I think the data is publicly available and unnecessary to push into the repo. The files are huge

2022-05-14 04:55 UTC, sameerz requested changes

2022-05-14 04:55 UTC, sameerz commented on examples/pcbs-benchmark/README.md
> +./pcbs-benchmark.sh /media/rjafri/data/data/mortgage_parquet/20m
Are there instructions on how to download the data? 

Also, another instance where we can remove the user name.

2022-05-14 04:55 UTC, sameerz commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +SPARK_TASK_CPUS=1
Why so many configs?  Especially when some of these are set to the default values?

2022-05-14 04:55 UTC, sameerz commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +SPARK_RAPIDS_MEMORY_GPU_POOL="ARENA"
Is ARENA necessary for this microbenchmark?

2022-05-14 04:55 UTC, sameerz commented on examples/pcbs-benchmark/src/main/scala/com/nvidia/CachePerfWriter.scala
> + */
Not necessary (do we have other submissions with developer names in the files?)

2022-05-14 04:58 UTC, sameerz requested changes

2022-05-14 04:58 UTC, sameerz commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +SPARK_RAPIDS_SQL_VARIABLEFLOATAGG_ENABLED="true"
Are these being removed in 22.06/

2022-05-16 17:42 UTC, razajafri commented on examples/pcbs-benchmark/README.md
> +./pcbs-benchmark.sh /media/rjafri/data/data/mortgage_parquet/20m
This isn't targeting any specific data. We can use any data we want. I can remove the username

2022-05-16 17:45 UTC, razajafri commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +SPARK_RAPIDS_MEMORY_GPU_POOL="ARENA"
I didn't play around with this setting, I asked in one of the standups and the impression I have is that we don't want to change this. Please correct me if I am wrong

2022-05-16 17:47 UTC, razajafri commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +SPARK_RAPIDS_SQL_VARIABLEFLOATAGG_ENABLED="true"
Yes, they are. I wasn't sure if we should remove them now or after the release

2022-05-16 17:47 UTC, razajafri commented on examples/pcbs-benchmark/src/main/scala/com/nvidia/CachePerfWriter.scala
> + */
This is my IDE's default behavior when I create new classes. I am not sure if we have other submissions, but I am not that particular about keeping my name in the file :smile:  I will remove it.

2022-05-16 17:55 UTC, razajafri commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +SPARK_TASK_CPUS=1
The default values could change in future which is why I set them.

2022-05-17 09:51 UTC, nvliyuan commented on examples/pcbs-benchmark/benchmark-multiple-files.sh
> +FILE_PREFIX="/media/rjafri/data/data/mortgage_parquet/"
can you please update the path to remove the name?

2022-05-17 09:51 UTC, nvliyuan commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +SPARK_HOME="/home/rjafri/spark-3.1.1-bin-hadoop3.2"
same here.

2022-05-17 09:51 UTC, nvliyuan commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +SPARK_TASK_RESOURCE_GPU_AMOUNT=0.8
can you please update the config to 1/cpu-core? otherwise we could get
```will result in wasted resources due to resource gpu limiting the number of runnable tasks per executor``` or 
```will result in wasted resources due to resource cpus limiting the number of runnable tasks per executor to``` warning

2022-05-17 09:51 UTC, nvliyuan commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +SPARK_SQL_SHUFFLE.PARTITIONS=200
a typo here, should update to `SPARK_SQL_SHUFFLE_PARTITIONS`

2022-05-17 09:51 UTC, nvliyuan commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +--conf spark.driver.extraJavaOptions=${SPARK_DRIVER_EXTRAJAVAOPTIONS} \
seems we need to update to 
` --conf spark.driver.extraJavaOptions="-ea -Duser.timezone=UTC" \
--conf spark.executor.extraJavaOptions="-ea -Duser.timezone=UTC -Dai.rapids.cudf.prefer-pinned=true" \ `
 otherwise we could get error `Error: Unrecognized option: -Duser.timezone=UTC`

2022-05-17 09:51 UTC, nvliyuan commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +--conf spark.rapids.sql.concurrentGpuTasks=${CONCURRENT_GPU_TASKS} \
seems typo here, need to update to `SPARK_RAPIDS_SQL_CONCURRENTGPUTASKS`

2022-05-17 09:51 UTC, nvliyuan commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +--conf spark.rapids.sql.concurrentGpuTasks=${CONCURRENT_GPU_TASKS} \
same typo , `SPARK_RAPIDS_SQL_CONCURRENTGPUTASKS`

2022-05-17 09:53 UTC, nvliyuan commented
@razajafri is the demo specific to spark3.1.X?  it works well with spark 3.1.1 and 3.1.2, but failed with spark3.2.0 due to spark version mismatch
```Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.internal.SessionState.executePlan(Lorg/apache/spark/sql/catalyst/plans/logical/LogicalPlan;)Lorg/apache/spark/sql/execution/QueryExecution;
  at org.apache.spark.sql.execution.columnar.Util$.$anonfun$readWriteCache$1(Util.scala:98)
  at scala.runtime.java8.JFunction1$mcJI$sp.apply(JFunction1$mcJI$sp.java:23)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
  at scala.collection.immutable.Range.foreach(Range.scala:158)
  at scala.collection.TraversableLike.map(TraversableLike.scala:286)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
  at org.apache.spark.sql.execution.columnar.Util$.readWriteCache(Util.scala:95)
  at org.apache.spark.sql.execution.columnar.Util$.runPcbsInternal(Util.scala:184)
  at org.apache.spark.sql.execution.columnar.Util$.runPcbs(Util.scala:190)
  at com.nvidia.BenchmarkPcbs$.main(RunPCBS.scala:28)
  at com.nvidia.BenchmarkPcbs.main(RunPCBS.scala)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)```

2022-05-17 09:58 UTC, nvliyuan commented
@razajafri can you please also make the spark master URL a variable?
such as `${BENCH_JAR} $url $data-path` in pcbs-benchmark.sh, then we don't need to hardcode in Util.scala
`.master("spark://raza-linux-2:7077")`

2022-05-18 20:08 UTC, razajafri commented
> @razajafri is the demo specific to spark3.1.X? it works well with spark 3.1.1 and 3.1.2, but failed with spark3.2.0 due to spark version mismatch
> 
> ```
> Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.internal.SessionState.executePlan(Lorg/apache/spark/sql/catalyst/plans/logical/LogicalPlan;)Lorg/apache/spark/sql/execution/QueryExecution;
>   at org.apache.spark.sql.execution.columnar.Util$.$anonfun$readWriteCache$1(Util.scala:98)
>   at scala.runtime.java8.JFunction1$mcJI$sp.apply(JFunction1$mcJI$sp.java:23)
>   at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
>   at scala.collection.immutable.Range.foreach(Range.scala:158)
>   at scala.collection.TraversableLike.map(TraversableLike.scala:286)
>   at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
>   at scala.collection.AbstractTraversable.map(Traversable.scala:108)
>   at org.apache.spark.sql.execution.columnar.Util$.readWriteCache(Util.scala:95)
>   at org.apache.spark.sql.execution.columnar.Util$.runPcbsInternal(Util.scala:184)
>   at org.apache.spark.sql.execution.columnar.Util$.runPcbs(Util.scala:190)
>   at com.nvidia.BenchmarkPcbs$.main(RunPCBS.scala:28)
>   at com.nvidia.BenchmarkPcbs.main(RunPCBS.scala)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)```
> ```

Yes, the benchmark was run on Spark 3.1.1 and it's very specific to it for now. We can in future make changes to it

2022-05-18 20:44 UTC, razajafri commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +--conf spark.driver.extraJavaOptions=${SPARK_DRIVER_EXTRAJAVAOPTIONS} \
fixed the problem by putting the variable in quotes

2022-05-18 20:44 UTC, razajafri commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +SPARK_TASK_RESOURCE_GPU_AMOUNT=0.8
What's the advantage of doing that? The user will still have to modify the variable cpu-core. Bash doesn't do floating-point arithmetic and I will have to rely on another util with no real benefit.

2022-05-18 20:49 UTC, razajafri commented
@nvliyuan I think I have addressed your concerns. PTAL

2022-05-19 03:28 UTC, nvliyuan commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +SPARK_TASK_RESOURCE_GPU_AMOUNT=0.8
agree, users will update that. But I assume that not all customers are familiar with this config, and during the test, I failed with error 
```
java.lang.AssertionError: assertion failed: The resource amount 0.8 must be either <= 0.5, or a whole number.
	at scala.Predef$.assert(Predef.scala:223)
	at org.apache.spark.resource.TaskResourceRequest.<init>(TaskResourceRequest.scala:41)
	at org.apache.spark.resource.TaskResourceRequests.resource(TaskResourceRequests.scala:72)
	at org.apache.spark.resource.ResourceUtils$.$anonfun$addTaskResourceRequests$1(ResourceUtils.scala:198)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
```
so not sure shall we add a comment [link](https://nvidia.github.io/spark-rapids/docs/tuning-guide.html#number-of-tasks-per-executor) to guide customers to set a right number to avoid failure

2022-05-19 06:08 UTC, nvliyuan commented on examples/pcbs-benchmark/src/main/scala/com/nvidia/CachePerfWriter.scala
> +    appendLine("Time taken for frst read: " + firstRead)
frst -> first

2022-05-19 06:56 UTC, nvliyuan commented
this is the perf result I get:
```
*****
PCBS
acc: true
Average write: 585
Time taken for frst read: 361
Average read (without first read): 142
acc: false
Average write: 3399
Time taken for frst read: 3619
Average read (without first read): 370
*******
DefaultSerializer
acc: true
Average write: 1429
Time taken for frst read: 946
Average read (without first read): 73
acc: false
Average write: 1298
Time taken for frst read: 1133
Average read (without first read): 54
```
Can I make a conclusion that if we enable PCBS(GpuInMemoryTableScanExec), we could get 5.8x(3399/585) speedups in ParquetCachedBatch write and 2.6x(370/1422) speedups in ParquetCachedBatch read if we enable the rapids plugin? And if we don't enable PCBS(GpuInMemoryTableScanExec),  there is no difference whether we enable rapids plugin?

2022-05-19 06:58 UTC, nvliyuan commented on examples/pcbs-benchmark/README.md
> +./pcbs-benchmark.sh <path to Parquet file>
since we updated the scripts, maybe also need to update the README.md doc

2022-05-19 07:05 UTC, nvliyuan commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +--conf spark.driver.extraJavaOptions=${SPARK_DRIVER_EXTRAJAVAOPTIONS} \
thanks, that also works

2022-05-19 23:54 UTC, razajafri commented
> this is the perf result I get:
> 
> ```
> *****
> PCBS
> acc: true
> Average write: 585
> Time taken for frst read: 361
> Average read (without first read): 142
> acc: false
> Average write: 3399
> Time taken for frst read: 3619
> Average read (without first read): 370
> *******
> DefaultSerializer
> acc: true
> Average write: 1429
> Time taken for frst read: 946
> Average read (without first read): 73
> acc: false
> Average write: 1298
> Time taken for frst read: 1133
> Average read (without first read): 54
> ```
> 
> Can I make a conclusion that if we enable PCBS(GpuInMemoryTableScanExec), we could get 5.8x(3399/585) speedups in ParquetCachedBatch write and 2.6x(370/142) speedups in ParquetCachedBatch read if we enable the rapids plugin? And if we don't enable PCBS(GpuInMemoryTableScanExec), there is no difference whether we enable rapids plugin?

Yes

2022-05-19 23:54 UTC, razajafri commented
@nvliyuan PTAL

2022-05-20 00:23 UTC, razajafri commented on examples/pcbs-benchmark/pcbs-benchmark.sh
> +SPARK_TASK_RESOURCE_GPU_AMOUNT=0.8
I have added the link to the tuning guide.

2022-05-20 01:52 UTC, nvliyuan commented
> @nvliyuan PTAL

@razajafri thanks, the PR looks good to me

2022-05-20 01:53 UTC, nvliyuan approved these changes

2022-05-20 02:02 UTC, nvliyuan commented
@razajafri since we just restructured the directories, I am not sure which directory this demo should belong to, I am confirming with @krajendrannv

2022-05-20 04:01 UTC, nvliyuan commented
> 

we can put it under `SQT+DF-Examples` folder

2022-05-23 01:53 UTC, nvliyuan commented
will close this pr and re-draft one @razajafri @sameerz

2022-05-23 01:53 UTC, closed without merging