v2206 release works
NVIDIA/spark-rapids-examples pull request #174
Opened 2022-06-02 04:43 UTC by nvliyuan

Signed-off-by: liyuan <yuali@nvidia.com>
The pr is to do release works for v22.06, including:

1. retest scala notebooks for xgboost v1.6.1 and update output infos
2. update databricks init script
3. rewording readme docs
4. fix dead links error

2022-06-02 15:58 UTC, viadea requested changes

2022-06-02 15:58 UTC, viadea commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
> +    "sudo wget -O xgboost4j-gpu_2.12-1.6.1.jar https://repo1.maven.org/maven2/ml/dmlc/xgboost4j-gpu_2.12/1.6.1/xgboost4j-gpu_2.12-1.6.1.jar\n",
We need to remove the existing xgboost jars from Databricks for 9.1 and 10.4 separately.
The jar paths are different, and I suggest we put some comment saying:
```
# for 9.1:
# rm ....jar
# for 10.4
rm ...jar
```
We can keep 10.4 solution uncommented.

2022-06-02 15:58 UTC, viadea commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
> +    "sudo cp /dbfs/FileStore/jars/xgboost4j-spark-gpu_2.12-1.6.1.jar /databricks/jars/spark--maven-trees--ml--9.x--xgboost-gpu--ml.dmlc--xgboost4j-spark-gpu_2.12--ml.dmlc__xgboost4j-spark-gpu_2.12__1
I suggest we remove the existing xgboost jar instead of copy the DMLC jar there. Because they are actually different versions.

2022-06-02 16:01 UTC, viadea requested changes

2022-06-02 16:01 UTC, viadea commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script-10.4.ipynb
> +    "sudo cp /dbfs/FileStore/jars/xgboost4j-gpu_2.12-1.6.1.jar /databricks/jars/spark--maven-trees--ml--10.x--xgboost-gpu--ml.dmlc--xgboost4j-gpu_2.12--ml.dmlc__xgboost4j-gpu_2.12__1.5.2.jar\n",
Same here. I suggest we firstly remove the existing xgboost jars from Databricks and then copy our 1.6.1 DMLC jars there. This is to avoid confusion to users since they are different version

2022-06-02 16:04 UTC, viadea requested changes

2022-06-02 16:04 UTC, viadea commented on docs/get-started/xgboost-examples/prepare-package-data/preparation-python.md
> +   * [XGBoost4j Package](https://repo1.maven.org/maven2/ml/dmlc/xgboost4j-gpu_2.12/1.6.1/)
I think in this "preparation-python.md", we need to keep the original 1.4.2-0.3.0 jar since this DMLC 1.6.1 jar does not have pyspark api. @GaryShen2008

2022-06-02 16:10 UTC, viadea requested changes

2022-06-02 16:10 UTC, viadea commented on examples/SQL+DF-Examples/micro-benchmarks/notebooks/micro-benchmarks-cpu.ipynb
> +      "Retry times : 1, TPC-DS Q14a subquery Microbenchmark takes 62.42 seconds\n",
Why we changed from NDS to TPCDS?

2022-06-06 03:28 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script-10.4.ipynb
> +    "sudo cp /dbfs/FileStore/jars/xgboost4j-gpu_2.12-1.6.1.jar /databricks/jars/spark--maven-trees--ml--10.x--xgboost-gpu--ml.dmlc--xgboost4j-gpu_2.12--ml.dmlc__xgboost4j-gpu_2.12__1.5.2.jar\n",
updated

2022-06-06 03:28 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
> +    "sudo cp /dbfs/FileStore/jars/xgboost4j-spark-gpu_2.12-1.6.1.jar /databricks/jars/spark--maven-trees--ml--9.x--xgboost-gpu--ml.dmlc--xgboost4j-spark-gpu_2.12--ml.dmlc__xgboost4j-spark-gpu_2.12__1
updated

2022-06-06 03:28 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
> +    "sudo wget -O xgboost4j-gpu_2.12-1.6.1.jar https://repo1.maven.org/maven2/ml/dmlc/xgboost4j-gpu_2.12/1.6.1/xgboost4j-gpu_2.12-1.6.1.jar\n",
updated

2022-06-06 03:39 UTC, nvliyuan commented on examples/SQL+DF-Examples/micro-benchmarks/notebooks/micro-benchmarks-cpu.ipynb
> +      "Retry times : 1, TPC-DS Q14a subquery Microbenchmark takes 62.42 seconds\n",
updated

2022-06-06 11:13 UTC, nvliyuan commented on docs/get-started/xgboost-examples/prepare-package-data/preparation-python.md
> +   * [XGBoost4j Package](https://repo1.maven.org/maven2/ml/dmlc/xgboost4j-gpu_2.12/1.6.1/)
revert

2022-06-07 19:06 UTC, viadea submitted a review, later dismissed

2022-06-08 05:30 UTC, nvliyuan commented
just update XBGoost readme because we revert removing python xgboost notebooks, @viadea can you please help re-review?

2022-06-08 05:32 UTC, GaryShen2008 commented on .github/workflows/signoff-check.yml
> -# Copyright (c) 2021, NVIDIA CORPORATION.
I think basically we add the year not replace it.
like 2021-2022.

2022-06-08 05:49 UTC, GaryShen2008 commented on README.md
> +Here is the list of notebooks in this repo:
Is here correct? 2 lines of "the list of..."?

2022-06-08 05:51 UTC, GaryShen2008 commented on README.md
> +| 9 | UDF | [StringWordCount](https://github.com/NVIDIA/spark-rapids-examples/blob/branch-22.06/examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/java/com/nvidia/spark/rapids/udf/hive/StringWord
Shall we use a relative link to the source code to avoid using a specific branch-22.06?

2022-06-08 05:58 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
> +3. [Download the Dockerfile](../../../../dockerfile/Dockerfile) into `${SPARK_HOME}`. (Here CUDA 11.0 is used as an example in the Dockerfile,
Why need to use relative path to replace the absolute path? I think the original one also works.

2022-06-08 05:58 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
> +Make sure you have prepared the necessary packages and dataset by following this [guide](../../../../docs/get-started/xgboost-examples/prepare-package-data/preparation-scala.md).
Why need to use relative path to replace the absolute path? I think the original one also works.

2022-06-08 05:59 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/prepare-package-data/preparation-python.md
> +Following this [guide](../../../../docs/get-started/xgboost-examples/building-sample-apps/python.md), you can get *samples.zip* and *main.py* and copy them to `/opt/xgboost`
Why need to use relative path to replace the absolute path? I think the original one also works.

2022-06-08 05:59 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/prepare-package-data/preparation-scala.md
> +Following this [guide](../../../../docs/get-started/xgboost-examples/building-sample-apps/scala.md), you can get *sample_xgboost_apps-0.2.2-jar-with-dependencies.jar* and copy it to `/opt/xgboost`
Why need to use relative path to replace the absolute path? I think the original one also works.

2022-06-08 06:06 UTC, GaryShen2008 commented on examples/ML+DL-Examples/Spark-cuML/pca/README.md
>        --conf spark.rapids.sql.enabled=true \
I think we only need either of --jar and extraClassPath.

2022-06-08 06:08 UTC, GaryShen2008 commented on examples/SQL+DF-Examples/micro-benchmarks/README.md
> +- **Intersect**: an operator used to remove duplicates in a dataframes.
```suggestion
- **Intersect**: an operator used to remove duplicates in a dataframe.
```

2022-06-08 06:13 UTC, GaryShen2008 commented on examples/SQL+DF-Examples/micro-benchmarks/README.md
> +this NDS dataset generator tool. All the queries are running on the SF3000(Scale Factors 3TB) dataset.
```suggestion
this NDS dataset generator tool. All the queries are running on the SF3000(Scale Factor 3000) dataset.
```

2022-06-08 06:17 UTC, GaryShen2008 commented on examples/SQL+DF-Examples/micro-benchmarks/notebooks/micro-benchmarks-cpu.ipynb
> +    "executorMem = os.getenv(\"EXECUTOR_MEM\", \"12g\")\n",
Any reason that CPU uses 12g executor memory, but GPU uses 16g?

2022-06-08 06:19 UTC, GaryShen2008 commented on examples/SQL+DF-Examples/micro-benchmarks/README.md
> +The queries are based on several tables in NDS parquet format with Decimal.
Seems the dataset path is useDecimal=false,useDate=true,filterNull=false.
Are you sure it's with Decimal?

2022-06-08 06:21 UTC, GaryShen2008 commented on examples/UDF-Examples/RAPIDS-accelerated-UDFs/README.md
> +--jars ${SPARK_RAPIDS_PLUGIN_JAR},${SPARK_RAPIDS_UDF_EXAMPLES_JAR} \
Same that I think we only need either of --jars or extraClassPath, if we don't use UCX.

2022-06-08 06:23 UTC, GaryShen2008 commented on examples/XGBoost-Examples/README.md
> +For each of these examples we have prepared a [sample dataset](https://github.com/NVIDIA/spark-rapids-examples/tree/branch-22.06/datasets)
Better to use relative path to avoid a branch name.

2022-06-08 06:25 UTC, GaryShen2008 commented on examples/XGBoost-Examples/README.md
> +Stand Alone or Kubernetes.
```suggestion
Standalone or Kubernetes.
```

2022-06-08 06:39 UTC, GaryShen2008 commented on examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage_gpu_crossvalidation.ipynb
> +    "what is new to xgboost-spark users is **rapids.CrossValidator**"
What does this mean?

2022-06-08 06:44 UTC, GaryShen2008 commented on examples/XGBoost-Examples/agaricus/notebooks/scala/agaricus-gpu.ipynb
> +       "dataRoot = /data\n",
Why adding these new variables? I don't find anywhere to use it.

2022-06-08 06:44 UTC, GaryShen2008 commented on examples/XGBoost-Examples/taxi/notebooks/scala/taxi-gpu.ipynb
> +       "dataRoot = /data\n",
No where to use dataRoot?

2022-06-08 06:49 UTC, GaryShen2008 commented on examples/XGBoost-Examples/agaricus/notebooks/scala/agaricus-gpu.ipynb
> +       "dataRoot = /data\n",
oh, it's output?

2022-06-08 06:54 UTC, GaryShen2008 commented on examples/XGBoost-Examples/agaricus/notebooks/scala/agaricus-gpu.ipynb
> +   "execution_count": 6,
nit: strange that the block count is 6, and previous is 1.

2022-06-08 09:32 UTC, nvliyuan commented on .github/workflows/signoff-check.yml
> -# Copyright (c) 2021, NVIDIA CORPORATION.
revert all copyright updates of no change files

2022-06-08 09:37 UTC, nvliyuan commented on README.md
> +Here is the list of notebooks in this repo:
removed the duplicate line.

2022-06-08 09:39 UTC, nvliyuan commented on README.md
> +| 9 | UDF | [StringWordCount](https://github.com/NVIDIA/spark-rapids-examples/blob/branch-22.06/examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/java/com/nvidia/spark/rapids/udf/hive/StringWord
updated

2022-06-08 09:41 UTC, nvliyuan commented on docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
> +3. [Download the Dockerfile](../../../../dockerfile/Dockerfile) into `${SPARK_HOME}`. (Here CUDA 11.0 is used as an example in the Dockerfile,
there is a bug in the link-checker that will mark the absolute path as dead links; I will revert the changes and file a bug for the tool

2022-06-08 09:44 UTC, nvliyuan commented on docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
> +Make sure you have prepared the necessary packages and dataset by following this [guide](../../../../docs/get-started/xgboost-examples/prepare-package-data/preparation-scala.md).
updated

2022-06-08 09:45 UTC, nvliyuan commented on docs/get-started/xgboost-examples/prepare-package-data/preparation-python.md
> +Following this [guide](../../../../docs/get-started/xgboost-examples/building-sample-apps/python.md), you can get *samples.zip* and *main.py* and copy them to `/opt/xgboost`
same reason, reverted

2022-06-08 09:46 UTC, nvliyuan commented on docs/get-started/xgboost-examples/prepare-package-data/preparation-scala.md
> +Following this [guide](../../../../docs/get-started/xgboost-examples/building-sample-apps/scala.md), you can get *sample_xgboost_apps-0.2.2-jar-with-dependencies.jar* and copy it to `/opt/xgboost`
same reason, reverted

2022-06-08 09:48 UTC, nvliyuan commented on examples/ML+DL-Examples/Spark-cuML/pca/README.md
>        --conf spark.rapids.sql.enabled=true \
updated

2022-06-08 09:49 UTC, nvliyuan commented on examples/SQL+DF-Examples/micro-benchmarks/README.md
> +this NDS dataset generator tool. All the queries are running on the SF3000(Scale Factors 3TB) dataset.
updated

2022-06-08 10:12 UTC, nvliyuan commented on examples/XGBoost-Examples/README.md
> +For each of these examples we have prepared a [sample dataset](https://github.com/NVIDIA/spark-rapids-examples/tree/branch-22.06/datasets)
updated

2022-06-08 10:13 UTC, nvliyuan commented on examples/XGBoost-Examples/README.md
> +Stand Alone or Kubernetes.
updated

2022-06-08 10:14 UTC, nvliyuan commented on examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage_gpu_crossvalidation.ipynb
> +    "what is new to xgboost-spark users is **rapids.CrossValidator**"
seems an info-log print by DMLC jar

2022-06-08 10:46 UTC, nvliyuan commented on examples/XGBoost-Examples/agaricus/notebooks/scala/agaricus-gpu.ipynb
> +   "execution_count": 6,
updated

2022-06-08 11:21 UTC, nvliyuan commented on examples/SQL+DF-Examples/micro-benchmarks/README.md
> +The queries are based on several tables in NDS parquet format with Decimal.
retest, the result is not much difference, updated the notebook

2022-06-14 07:20 UTC, nvliyuan commented
please do not merge until rapids plugin v22.06 release

2022-06-17 11:01 UTC, nvliyuan commented
@viadea @GaryShen2008 just update the cuspatial doc/scripts; can you please help re-review?

2022-06-17 17:55 UTC, viadea approved these changes

2022-06-22 03:01 UTC, merged