Add criteo training example
NVIDIA/spark-rapids-examples pull request #18
Opened 2021-08-31 15:57 UTC by wjxiz1992

- criteo training example shows the combination of NVTabular TensorFlow Horovod and Spark
- this example compared Petastorm vs NVTabular dataloader

Signed-off-by: wjxiz1992 <wjxiz1992@gmail.com>

2021-09-07 00:28 UTC, wjxiz1992 commented
@nvliyuan @GaryShen2008 Hi, I added a notebook for demo and also some markdown comments there, please help view and feedback! thanks!

2021-09-07 00:52 UTC, GaryShen2008 commented on examples/criteo_train/Criteo Training.ipynb
> +    "The model is compose by mainly 2 parts: embedding layers and fully-connected layers."
compose => composed

2021-09-07 01:08 UTC, wjxiz1992 commented on examples/criteo_train/Criteo Training.ipynb
> +    "The model is compose by mainly 2 parts: embedding layers and fully-connected layers."
Corrected.

2021-09-07 05:49 UTC, nvliyuan reviewed
Names need to be consistent `tf-hvd-train-pure:0.1`

2021-09-07 05:55 UTC, nvliyuan commented on examples/criteo_train/README.md
> +nvidia-docker build -f Dockerfile -t nvspark/tf-hvd-train:0.1 .
Names need to be consistent

2021-09-07 06:06 UTC, wjxiz1992 commented on examples/criteo_train/README.md
> +nvidia-docker build -f Dockerfile -t nvspark/tf-hvd-train:0.1 .
Updated.

2021-09-08 07:48 UTC, nvliyuan commented on examples/criteo_train/Dockerfile
> +RUN pip uninstall tensorflow -y; pip install tf-nightly==2.7.0.dev20210722
Do we need to change tf-nightly to tensorflow?

2021-09-08 11:05 UTC, wjxiz1992 commented on examples/criteo_train/Dockerfile
> +RUN pip uninstall tensorflow -y; pip install tf-nightly==2.7.0.dev20210722
Updated but re-install keras-nightly with specific version.

2021-09-09 09:06 UTC, nvliyuan commented
Should we add a description in README.md about this example? So that customers will know it on the front page.

2021-09-13 03:51 UTC, GaryShen2008 requested changes

2021-09-13 03:51 UTC, GaryShen2008 commented on examples/criteo_train/Dockerfile
> +ARG IMAGE=nvcr.io/nvidia/tensorflow:21.03-tf2-py3
CopyRight?

2021-09-13 03:51 UTC, GaryShen2008 commented on examples/criteo_train/README.md
> +nvidia-docker build -f Dockerfile -t nvspark/tf-hvd-train:0.1 .
Do we need nvidia-docker to build dockerfile?

2021-09-13 03:51 UTC, GaryShen2008 commented on examples/criteo_train/README.md
> +if you only want to try in a node with only 1 GPU, please modify the GPU number per worker in `$SPARK_HOME/conf/spark-env.sh` before you launch spark workers becasue the docker image is targeted for
Nit: if => If

2021-09-13 03:51 UTC, GaryShen2008 commented on examples/criteo_train/criteo_keras.py
> +import argparse
Copyright?

2021-09-13 04:36 UTC, wjxiz1992 commented on examples/criteo_train/README.md
> +nvidia-docker build -f Dockerfile -t nvspark/tf-hvd-train:0.1 .
Yes, there're also Tensorflow and horovod installation in the Dockerfile, and they will require GPU to do check according to my test.

2021-09-13 04:36 UTC, wjxiz1992 commented on examples/criteo_train/Dockerfile
> +ARG IMAGE=nvcr.io/nvidia/tensorflow:21.03-tf2-py3
Added.

2021-09-13 04:36 UTC, wjxiz1992 commented on examples/criteo_train/README.md
> +if you only want to try in a node with only 1 GPU, please modify the GPU number per worker in `$SPARK_HOME/conf/spark-env.sh` before you launch spark workers becasue the docker image is targeted for
Updated.

2021-09-13 04:36 UTC, wjxiz1992 commented on examples/criteo_train/criteo_keras.py
> +import argparse
Added

2021-09-14 01:41 UTC, wjxiz1992 commented
> Should we add a description in README.md about this example? So that customers will know it on the front page.

Added. @nvliyuan

2021-09-23 05:16 UTC, wjxiz1992 commented
Hi, can I get another round review for the comments? thx!

2021-09-23 05:59 UTC, merged