refine cupsatial demo to make it more clear for customers
NVIDIA/spark-rapids-examples pull request #187
Opened 2022-06-24 06:14 UTC by nvliyuan

refine cupsatial demo to make it more clear for customers
- update cuda pub key to avoid GPG error in databricks docker file
- update performance

Signed-off-by: liyuan <yuali@nvidia.com>

2022-07-04 22:28 UTC, sameerz reviewed
The command `docker build -f Dockerfile . -t build-spark-cuspatial` on line 44 is failing.  I get the following: 

```ERROR conda.cli.main_run:execute(49): `conda run /bin/bash -c conda install -c rapidsai-nightly -c nvidia -c conda-forge -c defaults libcuspatial=22.06 python=3.8 -y` failed. (See above for error)```

Is this failing because we are mixing 22.06 and 22.08-SNAPSHOT? 

Detailed error in https://gist.github.com/sameerz/544c046bf0b13683288df846d5d5673f

2022-07-05 02:31 UTC, nvliyuan commented
> Detailed error in https://gist.github.com/sameerz/544c046bf0b13683288df846d5d5673f

yes, I can reproduce it by running docker build without cache, update the docker file

2022-07-05 03:55 UTC, sameerz commented
> > Detailed error in https://gist.github.com/sameerz/544c046bf0b13683288df846d5d5673f
> 
> yes, I can reproduce it by running docker build without cache, update the docker file

I can build the docker file now and was able to build the spark-cuspatial-22.08.0-SNAPSHOT.jar.  

Do we want to update lines 66-69 in README.md to refer to 22.06 and 22.08-SNAPSHOT instead of 22.04 and 22.06-SNAPSHOT?

2022-07-05 06:30 UTC, nvliyuan commented
> Do we want to update lines 66-69 in README.md to refer to 22.06 and 22.08-SNAPSHOT instead of 22.04 and 22.06-SNAPSHOT?

updated, thanks

2022-07-08 15:44 UTC, nvliyuan commented
Add CPU notebook run on databricks

2022-07-11 03:29 UTC, NvTimLiu commented on examples/UDF-Examples/Spark-cuSpatial/README.md
>  interface to call the cuSpatial functions through JNI. It can be run on a distributed Spark cluster with scalability.
We don't have CI nightly job to run cuSpatial notebooks, suppose we need to add them to the examples nightly CI.

2022-07-11 03:32 UTC, nvliyuan commented on examples/UDF-Examples/Spark-cuSpatial/README.md
>  interface to call the cuSpatial functions through JNI. It can be run on a distributed Spark cluster with scalability.
yes, I will list a file about where and how to get the input datasets after this pr #191 merged.

2022-07-11 03:42 UTC, NvTimLiu approved these changes
LGTM

2022-07-13 17:08 UTC, viadea requested changes

2022-07-13 17:08 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +1. Set up a Databricks cluster with Databricks Runtime Version: Standard Runtime 10.3,
```suggestion
1. Create a Databricks cluster. For example, Databricks Runtime 10.3.
```

2022-07-13 17:08 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +2. Install the Sedona jars and Sedona Python on Databricks using Databricks default web UI.
```suggestion
2. Install the Sedona jars and Sedona Python libs on Databricks using web UI. 
```

2022-07-13 17:08 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +   * For enabling python support, from the Libraries tab install from PyPI
```suggestion
   * To enable python support, install below python lib from PyPI in Libraries tab 
```

2022-07-13 17:26 UTC, viadea commented
@nvliyuan in the CPU notebook, the last command is too long:
```
result = spark.sql("SELECT polygons.*, pointtable.* FROM polygons , pointtable WHERE ST_Contains(polygons.geometry, ST_Point(pointtable.x, pointtable.y))")
```

Can you split the SQL into multi-lines?

2022-07-14 01:48 UTC, nvliyuan commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +4. Restart the cluster because the libraries installed via UI are installed after the cluster has already started,
@viadea yes, updated

2022-07-14 22:37 UTC, viadea requested changes

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +### GPU Demo Run on AWS Databricks
```suggestion
### GPU Demo on AWS Databricks
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +### CPU Demo Run on AWS Databricks
```suggestion
### CPU Demo on AWS Databricks
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
>  1. essential build tools:
```suggestion
1. Essential build tools:
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +First you need to build the UDF Jar file from source code before running this demo.
```suggestion
Firstly build the UDF JAR from source code before running this demo.
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +You can do it [in Docker](#build-in-docker) with the provided [Dockerfile](Dockerfile).
```suggestion
You can build the JAR [in Docker](#build-in-docker) with the provided [Dockerfile](Dockerfile), 
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
>  or you can build it [in local](#build-in-local) machine after some prerequisites.
```suggestion
or [in local machine](#build-in-local-machine) after prerequisites.
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
>  ### Build in Local:
```suggestion
### Build in local machine:
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
>      # get libcuspatial from conda
```suggestion
    # Install libcuspatial from conda
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +5. Get the code, then run `mvn package`.
```suggestion
5. Build the JAR using `mvn package`.
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +6. You'll get `spark-cuspatial-<version>.jar` in the target folder.
```suggestion
6. `spark-cuspatial-<version>.jar` will be generated in the target folder.
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
>      Install it by running the command below.
```suggestion
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
>  3. Download spark-rapids jars
```suggestion
3. Download Spark RAPIDS JAR
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
>     * [spark-rapids v22.06.0](https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark_2.12/22.06.0/rapids-4-spark_2.12-22.06.0.jar) or above
```suggestion
   * [Spark RAPIDS JAR v22.06.0](https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark_2.12/22.06.0/rapids-4-spark_2.12-22.06.0.jar) or above
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +    Copy spark-rapids & `spark-cuspatial-<version>.jar` to `/data/cuspatial_data/jars`.
```suggestion
    Copy Spark RAPIDS JAR and `spark-cuspatial-<version>.jar` to `/data/cuspatial_data/jars/`.
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +4. Prepare the dataset & jars. Copy the sample dataset from [cuspatial_data](../../../datasets/cuspatial_data.tar.gz) to `/data/cuspatial_data`.
```suggestion
4. Prepare sample dataset and JARs. Copy the [sample dataset](../../../datasets/cuspatial_data.tar.gz) to `/data/cuspatial_data/`.
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +    If you build the `spark-cuspatial-22.08.0-SNAPSHOT.jar` in docker, please copy the jar from docker to local:
```suggestion
    If you build the `spark-cuspatial-<version>.jar` in docker, please copy the jar from docker to local:
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +    docker cp your-instance:/root/spark-rapids-examples/examples/UDF-Examples/Spark-cuSpatial/target/spark-cuspatial-22.08.0-SNAPSHOT.jar ./your-local-path
```suggestion
    docker cp YOUR_DOCKER_CONTAINER:/PATH/TO/spark-cuspatial-<version>.jar ./YOUR_LOCAL_PATH
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +    You can use your own path, but remember to update the paths in `gpu-run.sh` accordingly.
```suggestion
    Note: update the paths in `gpu-run.sh` accordingly.
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
>   Something different from the document.
```suggestion
 Below are some different steps since a custom docker image is used with Databricks:
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +  You should choose a Standard version of the Runtime version like `Runtime: 9.1 LTS(Scala 2.12, Spark 3.1.2)` and
```suggestion
  Choose a non-ML Databricks Runtime such as `Runtime: 9.1 LTS(Scala 2.12, Spark 3.1.2)` and
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +  choose GPU instance type like `g4dn.xlarge`. Note that ML runtime does not support customized docker container.
```suggestion
  choose GPU AWS instance type such as `g4dn.xlarge`. Note that ML runtime does not support customized docker container with below messages:
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +  If you choose a ML version, it says `Support for Databricks container services requires runtime version 5.3+`
```suggestion
`Support for Databricks container services requires runtime version 5.3+` 
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
>      * For the other configurations, you can follow the get-started document.
```suggestion
    * Follow the Databricks get-started document for other steps.
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +4. Import the Library `spark-cuspatial-22.08.0-SNAPSHOT.jar` to the Databricks, then install it to your cluster.
```suggestion
4. Upload `spark-cuspatial-<version>.jar` on dbfs and then install it in Databricks cluster.
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
>  5. Import [cuspatial_sample.ipynb](notebooks/cuspatial_sample_db.ipynb) to your workspace in Databricks. Attach to your cluster, then run it.
```suggestion
5. Import [cuspatial_sample.ipynb](notebooks/cuspatial_sample_db.ipynb) to Databricks workspace, attach it to Databricks cluster and run it.
```

2022-07-14 22:37 UTC, viadea commented on examples/UDF-Examples/Spark-cuSpatial/README.md
> +4. Upload the sample data files to DBFS, start the cluster, attach the [notebook](notebooks/spacial-cpu-apache-sedona_db.ipynb) to the cluster, and run all cells.
```suggestion
4. Upload the sample data files to DBFS, start the cluster, attach the [notebook](notebooks/spacial-cpu-apache-sedona_db.ipynb) to the cluster, and run it.
```

2022-07-15 05:36 UTC, nvliyuan commented
> Can you split the SQL into multi-lines?



> @nvliyuan in the CPU notebook, the last command is too long:
> 
> ```
> result = spark.sql("SELECT polygons.*, pointtable.* FROM polygons , pointtable WHERE ST_Contains(polygons.geometry, ST_Point(pointtable.x, pointtable.y))")
> ```
> 
> Can you split the SQL into multi-lines?

sure, updated

2022-07-18 17:16 UTC, viadea approved these changes

2022-07-19 02:07 UTC, merged