initial commit: modified scala etls to accept Fannie Mae data
NVIDIA/spark-rapids-examples pull request #191
Opened 2022-06-24 14:33 UTC by SurajAralihalli

Signed-off-by: Suraj Aralihalli <suraj.ara16@gmail.com>

2022-06-25 03:23 UTC, nvliyuan commented
please ignore the markdown links checker warnings, I file an [issue](https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/142) for this.

2022-06-25 04:48 UTC, viadea commented
@SurajAralihalli @nvliyuan Could you also check why markdown link failed:
```
[✖] /docs/get-started/xgboost-examples/on-prem-cluster/standalone-scala.md → Status: 400 [Error: ENOENT: no such file or directory, access '/docs/get-started/xgboost-examples/on-prem-cluster/standalone-scala.md'] {
[56](https://github.com/NVIDIA/spark-rapids-examples/runs/7051224566?check_suite_focus=true#step:5:57)
  errno: -2,
[57](https://github.com/NVIDIA/spark-rapids-examples/runs/7051224566?check_suite_focus=true#step:5:58)
  code: 'ENOENT',
[58](https://github.com/NVIDIA/spark-rapids-examples/runs/7051224566?check_suite_focus=true#step:5:59)
  syscall: 'access',
[59](https://github.com/NVIDIA/spark-rapids-examples/runs/7051224566?check_suite_focus=true#step:5:60)
  path: '/docs/get-started/xgboost-examples/on-prem-cluster/standalone-scala.md'
[60](https://github.com/NVIDIA/spark-rapids-examples/runs/7051224566?check_suite_focus=true#step:5:61)
}
```

2022-06-27 01:45 UTC, nvliyuan commented
> Could you also check why markdown link failed:
the link is not dead, I believe it is a bug in the link checker.

2022-07-12 09:54 UTC, nvliyuan commented on examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL.ipynb
>     "source": [
I believe we had a mistake here before, for `spark.sql.files.maxPartitionBytes` 2G is big enough.

2022-07-12 09:59 UTC, nvliyuan commented
> @viadea the link checker validates only http/https links and marks any references(links) to the files within the repo as failed `(Eg: /docs/get-started/xgboost-examples/building-sample-apps/scala.md)`

let me give another push to see who can help on this [issue](https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/142)

2022-07-13 07:08 UTC, nvliyuan commented on examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL.ipynb
>     "source": [
since `spark.rapids.sql.incompatibleOps.enabled` is true by default now, maybe we can remove the config.

2022-07-13 08:57 UTC, nvliyuan commented
since the output of mortgage-ETL.ipynb can be the input of mortgage-gpu.ipynb,  it would be nice if we update the mortgage-gpu.ipynb about the data loading part. It will be something like:
```
df = spark.read.parquet("your etl notebook output path")
splits = df.randomSplit([0.8, 0.2])
train_data = splits[0]
trans_data = splits[1]
```

2022-07-13 09:08 UTC, nvliyuan commented
@viadea shall we keep a sample mortgage dataset and add a declaration for convenience? So that customers do not need to get the dataset from the Fannie Mae website.

2022-07-13 16:10 UTC, viadea commented
> 

I think we should not. And that is the same reason why we have this PR to use raw data.

2022-07-13 17:16 UTC, viadea commented on examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL.ipynb
>     "source": [
yes the key is to keep only non-default settings for spark rapids based on current GA version -- say 2206.

2022-07-15 06:28 UTC, nvliyuan approved these changes

2022-07-18 22:16 UTC, viadea commented
One thing: When reading from raw CSV, there is no header in those CSV files.
But in notebook I found 
```
val reader = sparkSession.read.option("header", true).schema(rawSchema)
```

We need to make sure the reading the raw CSV to use header=false.

2022-07-18 22:43 UTC, viadea requested changes
Make sure ETL reading is reading CSV without header, and ETL writing is writing to parquet files in all notebooks(scala/python.)

2022-07-19 11:14 UTC, nvliyuan commented on examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL+XGBoost.ipynb
> +    "      StructField(\"orig_upb\", IntegerType()),\n",
we should keep the data type consistent

2022-07-20 13:29 UTC, SurajAralihalli commented on examples/XGBoost-Examples/mortgage/notebooks/python/MortgageETL.ipynb
> +    "    splits[0].coalesce(1).write.format('csv').save(output_path_train, header = 'true', mode=\"overwrite\")\n",
Noted.

2022-07-20 22:19 UTC, viadea requested changes

2022-07-20 22:19 UTC, viadea commented on examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-ETL.ipynb
> +    "  train.write.mode(\"overwrite\").parquet(new Path(outPath, \"train\").toString)\n",
Here we save the rawDF to parquet files, and then calculate rawDF again to do the 20-80 split. 
Is this the best logic for performance?
Should we : Save the rawDF to parquet files, and then read it back to do the 20-80 split to save the calculation again? 
Could you help test it this new approach's performance to see if this is the best logic?

2022-07-21 17:28 UTC, viadea approved these changes

2022-07-25 05:45 UTC, nvliyuan approved these changes

2022-07-25 05:45 UTC, merged