add micro-benchmarks notebooks
NVIDIA/spark-rapids-examples pull request #20
Opened 2021-09-10 09:15 UTC by nvliyuan

Signed-off-by: Yuan Li <yuali@yuali-mlt.client.nvidia.com>
add micro-benchmark notebooks

2021-09-10 09:28 UTC, nvliyuan commented
@GaryShen2008 @viadea Can you please help review the PR? The only difference from our internal repo is hiding the ip&port. Thanks

2021-09-10 16:39 UTC, viadea requested changes

2021-09-10 16:39 UTC, viadea commented on README.md
> +The microbenchmark on [RAPIDS Accelerator For Apache Spark](https://nvidia.github.io/spark-rapids/) is to identify, test and analyze the best queries which can be accelerated on the GPU.
Normally for each line, we do not put more than 100 characters as the best practice.
Could you wrap each line?

2021-09-10 16:39 UTC, viadea commented on README.md
> +// Generate the SF3000(Scale Factors 3TB) dataset
We can remove this comment in the command line

2021-09-10 16:39 UTC, viadea commented on README.md
> +You can see some queries running result give a better performance running the second time, it can be caused by many reasons such as JVM JIT or initialization overhead or caching input data in the OS
```suggestion
You can see some queries are faster in the second time, it can be caused by many reasons such as JVM JIT or initialization overhead or caching input data in the OS page cache, etc.
```

2021-09-10 16:39 UTC, viadea commented on README.md
> +You can get a clear and visual impression of the improved performance with or without the benefits of post-running. The improved performance is influenced by many conditions, including the dataset sc
```suggestion
You can get a clear and visual impression of the improved performance with or without the benefits of post-running. The improved performance is influenced by many conditions, including the dataset's scale factors or the GPU card.
```

2021-09-10 16:39 UTC, viadea commented on README.md
> +If the application running time is too long or failed, you can run the queries on a smaller dataset.
```suggestion
If the application ran for too long or even failed, you can run the queries on a smaller dataset.
```

2021-09-10 16:39 UTC, viadea commented on examples/micro-benchmarks/notebooks/micro-benchmarks-cpu.ipynb
> +    "# but on large clusters with large parquet files the splittable portions of the parquet files end up not being distributed as evenly \n",
```suggestion
    "# but on large clusters with large parquet files the splittable portions of the parquet files end up not being distributed evenly \n",
```

2021-09-10 16:39 UTC, viadea commented on examples/micro-benchmarks/notebooks/micro-benchmarks-cpu.ipynb
> +    "# and it is faster to repartition the data to redistribute the data than it is to deal with the skew.\n",
```suggestion
    "# and it is faster to re-partition the data to redistribute it than to deal with skew.\n",
```

2021-09-10 16:39 UTC, viadea commented on examples/micro-benchmarks/notebooks/micro-benchmarks-cpu.ipynb
> +    "This is a microbenchmark about windowing expressions running on CPU mode. The subquery calculates the average ss_sales_price of a fix window function partition by ss_customer_sk, and the parent
```suggestion
    "This is a microbenchmark about windowing expressions running on CPU mode. The sub-query calculates the average ss_sales_price of a fixed window function partition by ss_customer_sk, and the parent query calculates the average price of the sub-query grouping by each customer."
```

2021-09-10 16:39 UTC, viadea commented on examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
> +    "This is a microbenchmark about Expand&HashAggregate expressions running on the GPU. The query calculates the distinct value of some dimension columns and average birth year by different c_saluta
Regarding "Because an additional shuffle involved by the repartition operator in CPU mode." What is the result for this sentence?

2021-09-10 16:39 UTC, viadea commented on examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
> +    "This is a microbenchmark about Expand&HashAggregate expressions running on the GPU. The query calculates the distinct value of some dimension columns and average birth year by different c_saluta
```suggestion
    "This is a microbenchmark about Expand&HashAggregate expressions running on the GPU. The query calculates the distinct value of some dimension columns and average birth year by different c_salutation of customers after grouping by c_current_hdemo_sk. You will see about 10x speedups in this query. Because an additional shuffle involved by the repartition operator in CPU mode. And GPUExpand and GPUHashAggregate is much faster than Expand and HashAggregate because GPU algorithms allow us to parallelize the computation and we can utilize most of the GPU cores. The tasks' duration in the third stage is less than one second but will cost 20x-40x while running on CPU. There will be a more significant performance improvement along with the increasing number of count distinct columns and aggregate functions."
```

2021-09-10 16:39 UTC, viadea commented on examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
> +    "This is a microbenchmark about windowing expressions running on GPU mode. The subquery calculates the average ss_sales_price of a fix window function partition by ss_customer_sk, and the parent
```suggestion
    "This is a microbenchmark about windowing expressions running on GPU mode. The sub-query calculates the average ss_sales_price of a fixed window function partition by ss_customer_sk, and the parent query calculates the average price of the sub-query grouping by each customer. You will see about 25x speedups in this query. The speedup mainly comes from GPUSort/GPUWindow/GPUHashAggregate. The avg aggregation function evaluates all rows which are generated by the sub-query's window function. There will be a more significant performance improvement along with the increasing number of sub-query aggregate functions."
```

2021-09-10 16:39 UTC, viadea commented on examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
> +    "Data skew is caused by many null values in the ss_customer_sk column. You will see about 80x speedups in this query. The heavier skew task a query got, the more improved performance we will get
```suggestion
    "Data skew is caused by many null values in the ss_customer_sk column. You will see about 80x speedups in this query. The heavier skew task a query has, the more improved performance we will get because GPU parallelizes the computation, CPU is limited to just a single core because of how the algorithms are written."
```

2021-09-10 16:39 UTC, viadea commented on examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
> +    "This is a microbenchmark about intersection operation running on GPU mode. The query calculates items in the same brand, class, and category that are sold in all three sales channels in two cons
```suggestion
    "This is a microbenchmark about intersection operation running on GPU mode. The query calculates items in the same brand, class, and category that are sold in all three sales channels in two consecutive years. You will see about 10x speedups in this query. This is a competition between high cardinality SortMergeJoin vs GpuShuffleHashJoin. The mainly improved performance comes from two SortMergeJoin(s) in this query running on CPU get converted to GpuShuffleHashJoin running on GPU."
```

2021-09-13 03:27 UTC, nvliyuan commented on README.md
> +The microbenchmark on [RAPIDS Accelerator For Apache Spark](https://nvidia.github.io/spark-rapids/) is to identify, test and analyze the best queries which can be accelerated on the GPU.
updated

2021-09-13 03:27 UTC, nvliyuan commented on README.md
> +// Generate the SF3000(Scale Factors 3TB) dataset
updated

2021-09-13 16:19 UTC, viadea approved these changes

2021-09-14 10:15 UTC, GaryShen2008 approved these changes

2021-09-14 14:58 UTC, merged