v23.04 release links updates
NVIDIA/spark-rapids-examples pull request #287
Opened 2023-04-24 07:53 UTC by nvliyuan

Signed-off-by: liyuan <yuali@nvidia.com>
update release versions for spark-rapids v23.04 release

2023-04-26 14:55 UTC, viadea requested changes

2023-04-26 14:55 UTC, viadea commented on docs/get-started/xgboost-examples/csp/databricks/databricks.md
> +     installed.  Users will need to use 23.02.0 or later on Databricks 11.3 LTS ML.
@sameerz should we suggest use only use 23.04 to run on 11.3 due to the issue?

2023-04-26 15:06 UTC, sameerz commented on docs/get-started/xgboost-examples/csp/databricks/databricks.md
> +     installed.  Users will need to use 23.02.0 or later on Databricks 11.3 LTS ML.
Yes, makes sense.

2023-04-26 15:11 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/databricks/databricks.md
> +     installed.  Users will need to use 23.02.0 or later on Databricks 11.3 LTS ML.
updated, thansk

2023-04-27 01:11 UTC, NvTimLiu commented on docs/get-started/xgboost-examples/csp/dataproc/gcp.md
> +    --master-machine-type=n2-standard-16 \
Why need to change this to n2 from n1, for performance require?

2023-04-27 01:12 UTC, NvTimLiu approved these changes
LGTM

2023-04-27 02:11 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/dataproc/gcp.md
> +    --master-machine-type=n2-standard-16 \
![image](https://user-images.githubusercontent.com/84758614/234741966-029a1b7e-09e7-4a2e-b17c-0a6f69c0a0f8.png)
because n1 instance is not recommended by gcp any more, if we manually create the cluster, we could only see n2 instances, and this is keep the same as [document](https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-gcp.html#create-a-dataproc-cluster-using-t4s)

2023-04-27 08:41 UTC, merged