add hashjoin benchmark and fix dead link issue
NVIDIA/spark-rapids-examples pull request #409
Opened 2024-07-18 08:51 UTC by nvliyuan

This pr is to :

- add hashjoin microbenchmark and update the latest performance
- fix #402 dead link issue

2024-07-18 14:04 UTC, jlowe reviewed
Need to update the [README](https://github.com/NVIDIA/spark-rapids-examples/blob/main/examples/SQL%2BDF-Examples/micro-benchmarks/README.md)

2024-07-18 15:56 UTC, viadea requested changes

2024-07-18 15:56 UTC, viadea commented on examples/SQL+DF-Examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
> +    "### HashJoin\n",
The "HashJoin" font is not bold as other titles?

2024-07-18 15:56 UTC, viadea commented on examples/SQL+DF-Examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
> +    "This is a microbenchmark for a HashJoin. The query on GPU will be more than 10x times faster than CPU based on the cluster in the readme."
Is it 10x or just 8.08x without enhanced configs on dataproc?

2024-07-19 05:56 UTC, nvliyuan commented on examples/SQL+DF-Examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
> +    "This is a microbenchmark for a HashJoin. The query on GPU will be more than 10x times faster than CPU based on the cluster in the readme."
8.08x is for dataproc, more than 10x(14x) is based on A100.

2024-07-19 05:59 UTC, nvliyuan commented on examples/SQL+DF-Examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
> +    "### HashJoin\n",
update the code cell to markdown cell

2024-07-19 06:04 UTC, nvliyuan commented
> Need to update the [README](https://github.com/NVIDIA/spark-rapids-examples/blob/main/examples/SQL%2BDF-Examples/micro-benchmarks/README.md)

updated

2024-07-19 14:07 UTC, jlowe commented on examples/SQL+DF-Examples/micro-benchmarks/README.md
> +- **Hash-join**: A common use for a hash join is to obtain all combinations of items.
Copy and paste error -- hash join is _not_ a way to generate all combinations of items.

2024-07-22 03:05 UTC, nvliyuan commented on examples/SQL+DF-Examples/micro-benchmarks/README.md
> +- **Hash-join**: A common use for a hash join is to obtain all combinations of items.
updated

2024-07-22 13:47 UTC, jlowe approved these changes

2024-07-23 00:18 UTC, merged