update v2112
NVIDIA/spark-rapids-examples pull request #64
Opened 2021-12-15 09:15 UTC by nvliyuan

Signed-off-by: liyuan <yuali@nvidia.com>
update v2112

2021-12-15 15:36 UTC, viadea requested changes

2021-12-16 00:57 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/csp/databricks/init-notebook-for-rapids-spark-xgboost-on-databricks-gpu-7.0-ml.ipynb
> +    "wget -O cudf-21.12.0.jar https://search.maven.org/remotecontent?filepath=ai/rapids/cudf/21.12.0/cudf-21.12.0.jar\n",
Good catch. I think we should verify on Databricks. We may need to change to ML 7.3/9.0

2021-12-16 03:00 UTC, viadea commented on docs/get-started/xgboost-examples/csp/databricks/init-notebook-for-rapids-spark-xgboost-on-databricks-gpu-7.0-ml.ipynb
> +    "wget -O cudf-21.12.0.jar https://search.maven.org/remotecontent?filepath=ai/rapids/cudf/21.12.0/cudf-21.12.0.jar\n",
I think we should update https://github.com/NVIDIA/spark-rapids-examples/blob/branch-21.12/docs/get-started/xgboost-examples/csp/databricks/databricks.md to to use Spark 3.1.2 instead of Spark 3.0.1, and use Databricks 9.1ML instead of 7.0 or 7.3.

2021-12-16 06:25 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/databricks/init-notebook-for-rapids-spark-xgboost-on-databricks-gpu-7.0-ml.ipynb
> +    "wget -O cudf-21.12.0.jar https://search.maven.org/remotecontent?filepath=ai/rapids/cudf/21.12.0/cudf-21.12.0.jar\n",
This notebook cannot work on ML 9.1, we should replace this notebook with an init_script.

2021-12-16 08:19 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/csp/databricks/databricks.md
> +   Standard_NC6s_v3.  For GCP, choose N1 or A2 instance types with GPUs.
Why need to mention GCP in databricks.md?

2021-12-16 08:46 UTC, wjxiz1992 commented on docs/get-started/xgboost-examples/csp/databricks/databricks.md
> +3. Choose the number of workers that matches the number of GPUs you want to use.
This sentence is incorrect or ambiguous. 

```suggestion
3. Choose the number of workers you want to use.
```

2021-12-16 08:46 UTC, wjxiz1992 commented on docs/get-started/xgboost-examples/csp/databricks/databricks.md
> +Create a Databricks cluster by going to Clusters, then clicking `+ Create Cluster`.  Ensure the
I just found there's no "Clusters" field in the left panel. Just a "+ Create".
```suggestion
Create a Databricks cluster by clicking "+ Create -> Cluster" on the left panel. Ensure the
```

2021-12-16 08:46 UTC, wjxiz1992 commented on docs/get-started/xgboost-examples/csp/databricks/databricks.md
> +   “Clusters” button on the left panel, then select your cluster.
```suggestion
   “Compute” button on the left panel, then select your cluster.
```

2021-12-16 08:46 UTC, wjxiz1992 commented on examples/Spark-DL/criteo_train/Dockerfile
> +ARG RMM_VER=v21.12.00
Please don't change the version here. According to my test, this has been broken since 21.10.
```suggestion
# Please don't change the version here in future release.
ARG RMM_VER=v21.08.00
```

2021-12-16 08:46 UTC, wjxiz1992 commented on examples/Spark-DL/criteo_train/Dockerfile
> +ARG CUDF_VER=v21.12.00
```suggestion
ARG CUDF_VER=v21.08.03
```

2021-12-16 08:56 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
>      "sudo cp /dbfs/FileStore/jars/xgboost4j-spark_3.0-1.4.2-0.2.0.jar /databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j-spark_2.12--ml.dmlc__xgboost4j-spark_2.12__1.0.0.jar\"\
The end of this notebook refers to "branch-21.10/examples/mortgage/notebooks/".
It should be changed to branch-21.12, I think.

2021-12-16 09:50 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
>      "sudo cp /dbfs/FileStore/jars/xgboost4j-spark_3.0-1.4.2-0.2.0.jar /databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j-spark_2.12--ml.dmlc__xgboost4j-spark_2.12__1.0.0.jar\"\
updated

2021-12-16 09:59 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/databricks/databricks.md
> +   Standard_NC6s_v3.  For GCP, choose N1 or A2 instance types with GPUs.
removed it

2021-12-16 10:36 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
>      "sudo cp /dbfs/FileStore/jars/xgboost4j-spark_3.0-1.4.2-0.2.0.jar /databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j-spark_2.12--ml.dmlc__xgboost4j-spark_2.12__1.0.0.jar\"\
The link should be changed to another path.

2021-12-16 23:41 UTC, viadea commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
>      "sudo cp /dbfs/FileStore/jars/xgboost4j-spark_3.0-1.4.2-0.2.0.jar /databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j-spark_2.12--ml.dmlc__xgboost4j-spark_2.12__1.0.0.jar\"\
Here the `sudo cp /dbfs/FileStore/jars/xgboost4j_3.0-1.4.2-0.2.0.jar /databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j_2.12--ml.dmlc__xgboost4j_2.12__1.0.0.jar` and `sudo cp /dbfs/FileStore/jars/xgboost4j-spark_3.0-1.4.2-0.2.0.jar /databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j-spark_2.12--ml.dmlc__xgboost4j-spark_2.12__1.0.0.jar` are wrong, right?

We just need to change it to:

```
sudo cp /dbfs/FileStore/jars/xgboost4j_3.0-1.4.2-0.2.0.jar /databricks/jars/
sudo cp /dbfs/FileStore/jars/xgboost4j-spark_3.0-1.4.2-0.2.0.jar /databricks/jars/
```

2021-12-16 23:43 UTC, viadea commented on docs/get-started/xgboost-examples/csp/databricks/init-notebook-for-rapids-spark-xgboost-on-databricks-gpu-7.0-ml.ipynb
> +    "wget -O cudf-21.12.0.jar https://search.maven.org/remotecontent?filepath=ai/rapids/cudf/21.12.0/cudf-21.12.0.jar\n",
If so, we do not even support ML 7.0 right? if so this notebook has to be tested and tailored to be compatible with ML 7.3 or 9.1 since those are the only versions we support. 

I am fine with leaving this as a followup action item later, if above tests need some time.

2021-12-17 02:31 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
>      "sudo cp /dbfs/FileStore/jars/xgboost4j-spark_3.0-1.4.2-0.2.0.jar /databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j-spark_2.12--ml.dmlc__xgboost4j-spark_2.12__1.0.0.jar\"\
updated

2021-12-17 03:28 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
>      "sudo cp /dbfs/FileStore/jars/xgboost4j-spark_3.0-1.4.2-0.2.0.jar /databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j-spark_2.12--ml.dmlc__xgboost4j-spark_2.12__1.0.0.jar\"\
Can we verify this change of XGBoost jar? I remember there're xgboost jars in databricks environment already. That's why we choose to replace the existing jars with our XGBoost jars.
Otherwise there'll be 2 versions of XGBoost jars. It may cause a problem.

2021-12-17 03:30 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
> +    "4. Import the mortgage example notebook from `https://github.com/NVIDIA/spark-rapids-examples/blob/branch-21.12/examples/mortgage/notebooks/python/mortgage-gpu.ipynb`\n",
The link here is wrong. Should it be https://github.com/NVIDIA/spark-rapids-examples/blob/branch-21.12/examples/Spark-ETL%2BXGBoost/mortgage/notebooks/python/mortgage-gpu.ipynb?

2021-12-17 07:30 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
>      "sudo cp /dbfs/FileStore/jars/xgboost4j-spark_3.0-1.4.2-0.2.0.jar /databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j-spark_2.12--ml.dmlc__xgboost4j-spark_2.12__1.0.0.jar\"\
verified and works
![image](https://user-images.githubusercontent.com/84758614/146506606-5f45b506-2ee5-4fae-a189-e40b04af4f8d.png)

2021-12-17 09:33 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
>      "sudo cp /dbfs/FileStore/jars/xgboost4j-spark_3.0-1.4.2-0.2.0.jar /databricks/jars/spark--maven-trees--ml--7.x--xgboost--ml.dmlc--xgboost4j-spark_2.12--ml.dmlc__xgboost4j-spark_2.12__1.0.0.jar\"\
add 7.3ML doc and init script and verified

2021-12-20 01:39 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script-7.3.ipynb
> +    "4. Import the mortgage example notebook from `https://github.com/NVIDIA/spark-rapids-examples/blob/branch-21.12/examples/mortgage/notebooks/python/mortgage-gpu.ipynb`\n",
https://github.com/NVIDIA/spark-rapids-examples/blob/branch-21.12/examples/mortgage/notebooks/python/mortgage-gpu.ipynb
This link is invalid.

2021-12-20 01:45 UTC, nvliyuan commented on docs/get-started/xgboost-examples/csp/databricks/generate-init-script-7.3.ipynb
> +    "4. Import the mortgage example notebook from `https://github.com/NVIDIA/spark-rapids-examples/blob/branch-21.12/examples/mortgage/notebooks/python/mortgage-gpu.ipynb`\n",
updated

2021-12-20 06:58 UTC, GaryShen2008 approved these changes

2021-12-20 07:46 UTC, merged