Update notebook examples
NVIDIA/spark-rapids-examples pull request #69
Opened 2021-12-20 11:28 UTC by NvTimLiu

1, Add variables to overwrite the spark resource configs, from https://github.com/NVIDIA/spark-rapids-examples/pull/49

2, Use the consistent `DATA_ROOT` environment to overwrite the root path of the datase, refer to https://github.com/NVIDIA/spark-rapids-examples/pull/34

Signed-off-by: Tim Liu <timl@nvidia.com>

2021-12-20 11:29 UTC, NvTimLiu commented on examples/Spark-ETL+XGBoost/taxi/notebooks/python/taxi-ETL.ipynb
> +    "dataRoot = os.getenv('DATA_ROOT', '/data')\n",
Use the consistent DATA_ROOT environment , refer to #49

2021-12-20 11:29 UTC, NvTimLiu commented on examples/Spark-ETL+XGBoost/taxi/notebooks/scala/taxi-ETL.ipynb
> +    "val dataRoot = sys.env.getOrElse(\"DATA_ROOT\", \"/data\")\n",
Use the consistent DATA_ROOT environment , refer to #34

2021-12-20 11:33 UTC, NvTimLiu commented on examples/micro-benchmarks/notebooks/micro-benchmarks-cpu.ipynb
> +    "# You need to update data path with your real path and hardare resource!\n",
Add variables to overwrite the spark resource configs, from #49;

We need overwrite the resources configurations on specified environments , e.g. CI hosts may not have so many CPU/GPU/Mem resources.

2021-12-20 11:34 UTC, NvTimLiu commented
This PR should also be cherry-pick to branch-21.12

2021-12-20 11:38 UTC, nvliyuan commented
we have three additional notebooks, should we also add these to ci jobs?
scala/mortgage-ETL.ipynb 
python/taxi-ETL.ipynb
scala/taxi-ETL.ipynb

2021-12-21 02:45 UTC, firestarman commented on examples/micro-benchmarks/notebooks/micro-benchmarks-cpu.ipynb
> +    "# You need to update data path with your real path and hardare resource!\n",
?
```suggestion
    "# You need to update data path with your real path and hardware resource!\n",
```

2021-12-21 02:58 UTC, nvliyuan requested changes

2021-12-21 02:58 UTC, nvliyuan commented on examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
>      "conf.set(\"spark.rapids.sql.concurrentGpuTasks\", \"4\")\n",
we may have oom issue while running benchmarks on some week performance GPU like T4 with high concurrentGpuTasks, can we also make concurrentGpuTasks variable?

2021-12-21 03:32 UTC, nvliyuan approved these changes

2021-12-21 03:38 UTC, merged