Reword doc v2202
NVIDIA/spark-rapids-examples pull request #83
Opened 2022-01-12 03:53 UTC by nvliyuan

Reword doc v2202

2022-01-12 13:48 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/notebook/python-notebook.md
> +you should change `--master` param according to your cluster deploy mode, if the deploy mode is yarn, you should set `--master yarn`.
The "deploy mode" may confuse the user. Spark-submit has a deploy mode like "cluster", "client".

2022-01-12 13:50 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/notebook/python-notebook.md
> +   Taxi and Agaricus ETL job and are the same, just change to [Taxi XGBoost Notebook](../../../../examples/Spark-ETL+XGBoost/taxi/notebooks/python/taxi-gpu.ipynb)
What does it mean "Taxi and Agaricus ETL job and are the same"?

2022-01-12 13:53 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/notebook/toree.md
> +At the end of this guide, the reader will be able to run a sample notebook that runs on NVIDIA GPUs.
nit: change "the reader" to "you". may be soft.

2022-01-12 13:54 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/notebook/toree.md
> +you should change `--master` param according to your cluster deploy mode, if the deploy mode is yarn, you should set `--master yarn`.
Same for the deploy mode. It confuses.

2022-01-12 13:55 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/notebook/toree.md
> +   Taxi and Agaricus ETL job and are the same, just change to [Taxi XGBoost Notebook](../../../../examples/Spark-ETL+XGBoost/taxi/notebooks/scala/taxi-gpu.ipynb)
Same comment for "Taxi and Agaricus ETL job and are the same"

2022-01-12 13:58 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
> +wget https://github.com/NVIDIA/spark-rapids-examples/raw/branch-21.12/dockerfile/Dockerfile
Is "branch-21.12" correct because this PR is for branch-22.02?

2022-01-12 14:04 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
> +to execute using a GPU that is already in use -- causing undefined behavior and errors.
A little strange English "execute using a GPU that is already in use"?

2022-01-12 14:10 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/on-prem-cluster/standalone-python.md
> +We use `SPARK_HOME` environment variable to point to the cluster's Apache Spark cluster.
"the cluster's Apache Spark cluster", a little weird.

2022-01-12 17:19 UTC, viadea requested changes

2022-01-12 17:19 UTC, viadea commented on docs/get-started/xgboost-examples/notebook/toree.md
>  Get Started with XGBoost4J-Spark with Apache Toree Jupyter Notebook
@nvliyuan Do you want to make the same changes based on my review comments in python-notebook.md ?

2022-01-12 17:19 UTC, viadea commented on docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
> +wget https://github.com/NVIDIA/spark-rapids-examples/raw/branch-21.12/dockerfile/Dockerfile
I guess this is correct for now since we normally do version change at 22.02 release time.

2022-01-12 17:19 UTC, viadea commented on examples/Spark-ETL+XGBoost/README.md
> +which is used in the Mortgage demo blow for quick download.
```suggestion
which is used in the Mortgage demo below for quick download.
```

2022-01-12 17:19 UTC, viadea commented on examples/Spark-ETL+XGBoost/README.md
> +We have three sub demos to demonstrate the Spark ETL + XGBoost process as Mortgage, Taxi and Agaricus(Agaricus demo has
```suggestion
We have three examples to demonstrate the Spark ETL + XGBoost process: Mortgage, Taxi and Agaricus(Agaricus demo has 
```

2022-01-12 17:19 UTC, viadea commented on examples/Spark-ETL+XGBoost/README.md
> +You have two ways to get start, you can start by running scala or python codes, or you can start by running notebooks.
```suggestion
Here are 2 ways to get started:
- Running Spark jobs
- Notebooks
```

2022-01-12 17:19 UTC, viadea commented on examples/Spark-ETL+XGBoost/README.md
> +### 1. Getting Started From Codes
```suggestion
### 1. Getting Started by running Spark jobs
```

2022-01-12 17:19 UTC, viadea commented on examples/Spark-ETL+XGBoost/README.md
> +### 2. Getting Started From Notebooks
```suggestion
### 2. Getting Started by using Notebooks
```

2022-01-13 02:57 UTC, nvliyuan commented on docs/get-started/xgboost-examples/notebook/toree.md
>  Get Started with XGBoost4J-Spark with Apache Toree Jupyter Notebook
yes, all docs should be consistent.

2022-01-13 02:59 UTC, nvliyuan commented
we also need to update top-level README.md

2022-01-13 03:22 UTC, nvliyuan commented on docs/get-started/xgboost-examples/notebook/toree.md
>  Get Started with XGBoost4J-Spark with Apache Toree Jupyter Notebook
updated toree.md, will update the same changes in pr #81

2022-01-13 03:24 UTC, nvliyuan commented on docs/get-started/xgboost-examples/notebook/python-notebook.md
> +you should change `--master` param according to your cluster deploy mode, if the deploy mode is yarn, you should set `--master yarn`.
updated

2022-01-13 03:25 UTC, nvliyuan commented on docs/get-started/xgboost-examples/notebook/python-notebook.md
> +   Taxi and Agaricus ETL job and are the same, just change to [Taxi XGBoost Notebook](../../../../examples/Spark-ETL+XGBoost/taxi/notebooks/python/taxi-gpu.ipynb)
updated

2022-01-13 03:25 UTC, nvliyuan commented on docs/get-started/xgboost-examples/notebook/toree.md
> +At the end of this guide, the reader will be able to run a sample notebook that runs on NVIDIA GPUs.
updated

2022-01-13 03:26 UTC, nvliyuan commented on docs/get-started/xgboost-examples/notebook/toree.md
> +you should change `--master` param according to your cluster deploy mode, if the deploy mode is yarn, you should set `--master yarn`.
updated

2022-01-13 03:26 UTC, nvliyuan commented on docs/get-started/xgboost-examples/notebook/toree.md
> +   Taxi and Agaricus ETL job and are the same, just change to [Taxi XGBoost Notebook](../../../../examples/Spark-ETL+XGBoost/taxi/notebooks/scala/taxi-gpu.ipynb)
updated

2022-01-13 03:42 UTC, nvliyuan commented on docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
> +to execute using a GPU that is already in use -- causing undefined behavior and errors.
change `that` to `which`

2022-01-13 03:50 UTC, nvliyuan commented on docs/get-started/xgboost-examples/on-prem-cluster/standalone-python.md
> +We use `SPARK_HOME` environment variable to point to the cluster's Apache Spark cluster.
reword this part in all related docs

2022-01-13 04:28 UTC, nvliyuan commented on docs/get-started/xgboost-examples/notebook/toree.md
>  Get Started with XGBoost4J-Spark with Apache Toree Jupyter Notebook
close pr #81 and merge it to this pr

2022-01-13 05:04 UTC, GaryShen2008 commented on README.md
>  [guide](/examples/Spark-cuML/pca/README.md).
Which link type is correct? 
[guide](/examples/Spark-cuML/pca/README.md)
vs
[guide](examples/Spark-DL/criteo_train/README.md)?

2022-01-13 05:09 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/notebook/python-notebook.md
> +
Why there're empty lines below?

2022-01-13 05:16 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/notebook/spylon.md
> +4. CLI to run scala notebook (e.g. [mortgage-gpu.ipynb](../../../../examples/Spark-ETL+XGBoost/mortgage/notebooks/scala/mortgage-gpu.ipynb))
Maybe to use the link type of /examples/Spark-ETL+XGBoost/... is much cleaner.

2022-01-13 05:28 UTC, nvliyuan commented on docs/get-started/xgboost-examples/notebook/spylon.md
> +4. CLI to run scala notebook (e.g. [mortgage-gpu.ipynb](../../../../examples/Spark-ETL+XGBoost/mortgage/notebooks/scala/mortgage-gpu.ipynb))
updated the ref links

2022-01-13 05:28 UTC, nvliyuan commented on docs/get-started/xgboost-examples/notebook/python-notebook.md
> +
deleted

2022-01-13 05:28 UTC, nvliyuan commented on README.md
>  [guide](/examples/Spark-cuML/pca/README.md).
both is correct, line 45 is better, updated

2022-01-13 05:46 UTC, GaryShen2008 commented on examples/Spark-ETL+XGBoost/README.md
> +which is used in the Mortgage demo blow for quick download.
```suggestion
which is used in the Mortgage demo below for quick download.
```

2022-01-13 06:11 UTC, nvliyuan commented on examples/Spark-ETL+XGBoost/README.md
> +which is used in the Mortgage demo blow for quick download.
this should already be updated in the latest commits.

2022-01-13 17:07 UTC, viadea requested changes

2022-01-13 17:07 UTC, viadea commented on docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
> +\* The timings in this Getting Started guide are only illustrative.
```suggestion
\* The timings in this Getting Started guide are only for illustrative purpose. 
```

2022-01-13 17:07 UTC, viadea commented on docs/get-started/xgboost-examples/on-prem-cluster/standalone-scala.md
>  1. Copy the spark configure file from template
```suggestion
1. Copy the spark configure file from template.
```

2022-01-13 17:07 UTC, viadea commented on docs/get-started/xgboost-examples/on-prem-cluster/standalone-scala.md
>  3. Start a Spark slave process:
```suggestion
3. Start a Spark slave process.
```

2022-01-13 17:07 UTC, viadea commented on docs/get-started/xgboost-examples/on-prem-cluster/standalone-scala.md
> +<sup>*</sup> The timings in this Getting Started guide are only illustrative.
```suggestion
<sup>*</sup> The timings in this Getting Started guide are only for illustrative purpose. 
```

2022-01-13 17:07 UTC, viadea commented on docs/get-started/xgboost-examples/on-prem-cluster/yarn-python.md
> +<sup>*</sup> The timings in this Getting Started guide are only illustrative.
```suggestion
<sup>*</sup> The timings in this Getting Started guide are only for illustrative purpose.
```

2022-01-13 17:07 UTC, viadea commented on docs/get-started/xgboost-examples/on-prem-cluster/yarn-scala.md
> +<sup>*</sup> The timings in this Getting Started guide are only illustrative.
```suggestion
<sup>*</sup> The timings in this Getting Started guide are only for illustrative purpose.
```

2022-01-14 03:35 UTC, nvliyuan commented on docs/get-started/xgboost-examples/notebook/spylon.md
> +    # Let's make the default password as '123456'
since I remove the masked hash password, this line also needs to be removed.

2022-01-14 14:04 UTC, GaryShen2008 commented on docs/get-started/xgboost-examples/notebook/toree.md
> +4. Install a new kernel with gpu enabled and lunch the notebook
```suggestion
4. Install a new kernel with gpu enabled and launch the notebook
```

2022-01-14 14:09 UTC, GaryShen2008 commented on examples/Spark-ETL+XGBoost/README.md
> +You can get a small size datasets for each example in the [datasets](../../datasets) folder.
```suggestion
You can get a small size dataset for each example in the [datasets](../../datasets) folder. 
```

2022-01-14 16:36 UTC, viadea approved these changes

2022-01-14 16:37 UTC, viadea commented
I approved with lots of above suggestions get done.
We can merge it firstly and fix more in the future.

2022-01-16 12:57 UTC, GaryShen2008 approved these changes

2022-01-17 02:55 UTC, merged